#!/usr/bin/env bash

# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

DT=$(date "+%Y%m%d-%H%M%S")
RUNS=1
if [[ "$#" -eq 1 ]]
then
    RUNS=$1
fi
for ((n=1;n<=$RUNS;n++))
    do python chrome_test_wf.py
done
mv results.csv "results_wf_$DT.csv"
mv summary.csv "summary_wf_$DT.csv"
